version: "2"

plugins:
  # official plugins
  duplication:
    enabled: true
    config:
      languages:
        - php:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2" # todo replace with PSR12 when Code Climate adds it
  phpmd:
    enabled: true
    checks:
      CleanCode/ElseExpression:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - "tests/**"

  # community-supported plugins
  markdownlint:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
      backward-compatibility-checks: true
      dead-code-detection: true

exclude_patterns:
  - "tests/"
