build:
  nodes:
    analysis_phpcs:
      tests:
        override:
          - phpcs-run --standard=PSR12
    analysis_scrutinizer:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
    analysis_shellcheck:
      tests:
        override:
          - shellcheck-run

filter:
  dependency_paths:
    - vendor/

tools:
  external_code_coverage: true
  # timeout: 600 # default timeout in seconds
