before_commands:
    - composer self-update
    - composer install --no-interaction --prefer-source

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage: true
    php_analyzer:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_loc:
        enabled: true
        excluded_dirs: [tests]
    php_mess_detector:
        enabled: true
        filter:
            paths: [src/*]
    php_pdepend:
        enabled: true
        excluded_dirs: [tests]
    php_sim:
        enabled: true
        filter:
            paths: [src/*]
