os: linux
dist: trusty

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm-3.30
  - nightly

jobs:
  allow_failures:
    - php: nightly

install:
  - composer self-update
  - composer global require 'fxp/composer-asset-plugin:*'
  - composer update --no-interaction --prefer-source
  - |
    COVERAGE_PHP_VERSION='5.6'
    if [ $TRAVIS_PHP_VERSION = $COVERAGE_PHP_VERSION ]; then
        # install and configure runkit extension
        pecl channel-update pecl.php.net
        pecl install runkit
        phpenv config-add tests/runkit/travis.ini

        # code coverage for Code Climate
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter

        # code coverage for Scrutinizer
        wget https://scrutinizer-ci.com/ocular.phar
    fi

before_script:
  - |
    if [ $TRAVIS_PHP_VERSION = $COVERAGE_PHP_VERSION ]; then
        PHPUNIT_FLAGS='--coverage-clover=coverage.clover'

        # code coverage for Code Climate
        ./cc-test-reporter before-build
    fi

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = $COVERAGE_PHP_VERSION ]; then
        # code coverage for Code Climate
        ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

        # code coverage for Scrutinizer
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
